import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type AppLanguage = 'zh-HK' | 'en';

type LanguageContextValue = {
  language: AppLanguage;
  isEnglish: boolean;
  toggleLanguage: () => void;
  setLanguage: (language: AppLanguage) => void;
  t: (zh: string, en: string) => string;
  tr: (value: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

const EN_TRANSLATIONS: Record<string, string> = {
  '中一級課程概覽': 'Secondary 1 Curriculum Overview',
  '中二級課程概覽': 'Secondary 2 Curriculum Overview',
  '中三級課程概覽': 'Secondary 3 Curriculum Overview',
  '歡迎, ': 'Welcome, ',
  '請選擇一個學習單元以開始。': 'Choose a learning unit to begin.',
  '學習進度': 'Learning Progress',
  '開始': 'Start',
  '高中 (S4-S6) 概覽': 'Senior Secondary (S4-S6) Overview',
  '必修部分 (Compulsory)': 'Compulsory Part',
  '選修部分 (Electives)': 'Electives',
  '學習資源 (Resources)': 'Resources',
  '專題活動 (Project)': 'Project Hub',
  '材料資料庫 (Materials DB)': 'Materials Database',
  'HKDSE 課程資源': 'HKDSE Resources',
  '教育局 · 香港中學課程': 'EDB · Hong Kong Secondary Curriculum',
  'HKDSE 設計與科技 / 設計與應用科技': 'HKDSE Design & Technology / Design and Applied Technology',
  '中一至中三': 'S1 to S3',
  '中四至中六': 'S4 to S6',
  '共用教學資源': 'Shared Resources',
  '設計與科技 (D&T)': 'Design and Technology (D&T)',
  '設計與應用科技 (DAT)': 'Design and Applied Technology (DAT)',
  'S1–S6 共用': 'Shared Across S1–S6',
  '模組說明 (Module Reference)': 'Module Reference',
  '模組及教學計劃總覽': 'Module and Teaching Plan Overview',
  '個案研究 (Case Studies) — 中一至中三': 'Case Studies — S1 to S3',
  '個案研究 (Case Studies) — 中四至中六': 'Case Studies — S4 to S6',
  '主題式學與教資源 (Thematic Resources)': 'Thematic Learning and Teaching Resources',
  '選修部分 (Elective Modules)': 'Elective Modules',
  'DSE 規定學生須「五選二」，點擊進入了解各模組內容。': 'DSE students choose two out of five electives. Click to explore each module.',
  '五選二': 'Choose 2 of 5',
  '點擊互動': 'Open Interaction',
  '收起': 'Collapse',
  '進入完整模組頁': 'Open Full Module Page',
  '互動遊戲': 'Interactive Activity',
  '學習標籤': 'Learning Tags',
  '課程重點': 'Key Learning Points',
  '學習資源中心': 'Resource Hub',
  '專題活動中心': 'Project Hub',
  '學習資源下載區 (Resource Download)': 'Resource Downloads',
  '必修部分 (Compulsory Areas)': 'Compulsory Areas',
  'DSE 必考 · 全部必修': 'Required in DSE · All Compulsory',
  '評估結構 (Assessment)': 'Assessment Structure',
  'DSE 公開考試 + 校本評核': 'DSE Public Exam + SBA',
  '卷一 Paper 1': 'Paper 1',
  '卷二 Paper 2': 'Paper 2',
  '校本評核 SBA': 'School-based Assessment (SBA)',
  '設計項目 (Design Project)': 'Design Project',
  '學習資源': 'Resources',
  'Resource Center': 'Resource Center',
  'Project Hub': 'Project Hub',
  '返回': 'Back',
  'Overview': 'Overview',
  'Sandbox': 'Sandbox',
  'Quiz': 'Quiz',
  'Module Quiz': 'Module Quiz',
  '提交答案': 'Submit Answers',
  '重試': 'Retry',
  '得分:': 'Score:',
  '完成所有題目後提交': 'Answer all questions before submitting',
  '材料資料庫 (Materials Database)': 'Materials Database',
  '探索木材、金屬、聚合物及智能材料的屬性與應用。利用過濾器或搜尋功能快速尋找合適的材料，為你的設計與製作打好基礎。': 'Explore the properties and uses of woods, metals, polymers, and smart materials. Use filters and search to quickly find suitable materials for your design and making work.',
  '搜尋材料名稱、用途或特性...': 'Search material name, use, or properties...',
  '查看詳細數據': 'View Detailed Data',
  '找不到符合條件的材料。': 'No matching materials found.',
  '清除搜尋條件': 'Clear Search',
  '主要特性': 'Key Properties',
  '常見用途': 'Common Uses',
  '硬度': 'Hardness',
  '抗拉強度': 'Tensile Strength',
  '工具及儀器安全 (Workshop Safety)': 'Workshop Safety',
  '識別工場內的潛在危險，確保工作環境安全。': 'Identify hazards in the workshop and keep the working environment safe.',
  '狀態': 'Status',
  '已發現': 'found',
  '點擊識別': 'Click to identify',
  '指引': 'Instructions',
  '點擊場景中的不安全物品或行為。尋找散落的物品、缺少的安全裝備或溢出物。': 'Click unsafe objects or behaviours in the scene. Look for loose items, missing safety equipment, or spills.',
  '繼續尋找！該區域是安全的。': 'Keep looking. That area is safe.',
  '檢查完成': 'Inspection Complete',
  '你已識別出所有危險。工場現在安全了。': 'You identified all hazards. The workshop is now safe.',
  '再次檢查': 'Inspect Again',
  '理論參考': 'Theory Reference',
  '機械結構 (Mechanisms)': 'Mechanisms',
  '嘗試不同的凸輪 (Cam) 形狀來控制從動件 (Follower) 的運動。': 'Try different cam profiles to control the motion of the follower.',
  '凸輪選擇 (Cam Profile)': 'Cam Profile Selection',
  '停止模擬': 'Stop Simulation',
  '開始模擬': 'Start Simulation',
  '目標': 'Goal',
  '選擇 ': 'Choose ',
  ' 使兔子突然跳起。': ' to make the rabbit jump suddenly.',
  '齒輪比計算器 (Gear Ratio Calculator)': 'Gear Ratio Calculator',
  '主動齒輪 (Driver) 齒數': 'Driver Gear Teeth',
  '從動齒輪 (Driven) 齒數': 'Driven Gear Teeth',
  '齒輪比': 'Gear Ratio',
  '速度比': 'Speed Ratio',
  '扭矩倍數': 'Torque Multiplier',
  '減速': 'Speed Reduction',
  '增速': 'Speed Increase',
  '增加扭力': 'Higher Torque',
  '減少扭力': 'Lower Torque',
  '齒輪比 = 從動齒數 ÷ 主動齒數  |  速度與扭矩成反比 (能量守恆)': 'Gear ratio = driven teeth ÷ driver teeth | Speed and torque are inversely related (energy conservation)',
  '系統與控制 (Systems & Control)': 'Systems and Control',
  '設計一個自動夜燈系統的邏輯電路。': 'Design the logic circuit for an automatic night light system.',
  '邏輯元件 (Logic Gates)': 'Logic Gates',
  '提示:': 'Hint:',
  '燈應該只在黑暗 ': 'The lamp should only turn on when it is dark ',
  '及 (AND)': 'and (AND)',
  ' 開關開啟時才亮起。': ' and the switch is on.',
  '光敏電阻': 'Light-dependent Resistor',
  '手動開關': 'Manual Switch',
  '系統輸出': 'System Output',
  '黑暗 (Dark)': 'Dark',
  '光亮 (Bright)': 'Bright',
  '總電源 (Master Power)': 'Master Power',
  '真值表 (Truth Table)': 'Truth Table',
  '輸出 (Q)': 'Output (Q)',
  '請先拖放一個邏輯閘以顯示真值表': 'Drag a logic gate first to display the truth table',
  '物料特性測試 (Material Properties Lab)': 'Material Properties Lab',
  '選擇一種物料並進行標準測試，觀察其物理特性。': 'Choose a material and run a standard test to observe its physical properties.',
  '1. 樣本選擇': '1. Select a Specimen',
  '2. 測試方法': '2. Test Method',
  '衝擊/硬度': 'Impact / Hardness',
  '熱特性': 'Thermal Properties',
  '表面硬度': 'Surface Hardness',
  '測試結果暫無數據。': 'No test data available.',
  'K3 物料分類 — EDB 課程重點': 'K3 Material Classification — EDB Key Points',
  '參考來源：EDB《設計與科技》課程指引 — 物料及資源（K3）；香港考試及評核局 DAT 課程大綱': 'Source: EDB Design and Technology Curriculum Guide — Materials and Resources (K3); HKEAA DAT syllabus',
  '正投影圖 (Orthographic Projection)': 'Orthographic Projection',
  '將正確的 2D 視圖與 3D L形塊模型進行配對。': 'Match the correct 2D views with the 3D L-shaped block model.',
  '旋轉 3D 模型': 'Rotate 3D Model',
  '將視圖拖曳到正確位置': 'Drag each view to the correct position',
  '投影正確 (Correct)': 'Projection Correct',
  'K6 設計呈現 — 正投影圖規則 (EDB 課程重點)': 'K6 Design Representation — Orthographic Projection Rules',
  'First-Angle Projection': 'First-Angle Projection',
  '三視圖排列': 'Arrangement of Three Views',
  '線型規範': 'Line Conventions',
  '尺寸標注 (Dimensioning)': 'Dimensioning',
  '中一至中六 共用學與教資源': 'Shared Learning and Teaching Resources for S1–S6',
  '以下資源適用於中一至中六 D&T / DAT 各年級，由教育局提供。': 'The following resources are applicable to D&T / DAT across S1–S6 and are provided by the Education Bureau.',
  '中四至中六 DAT 校本評核 (SBA) 資源': 'S4–S6 DAT SBA Resources',
  '模組代碼速查 (Module Code Reference)': 'Module Code Reference',
  '核心模組 (Core K)': 'Core Modules (K)',
  '延伸模組 (Extension E)': 'Extension Modules (E)',
  'IB MYP Design — 課程宗旨': 'IB MYP Design — Course Aim',
  'MYP 設計周期 / IBO 評估準則': 'MYP Design Cycle / IBO Assessment Criteria',
  'Criteria A-D · 各佔 8 分': 'Criteria A–D · 8 marks each',
  'IBO Standard Fit': 'IBO Standard Fit',
  '在 MYP Design 中，學生並不是只被評核「做出成品」，而是按 IBO 的四個準則進行全面評估：': 'In MYP Design, students are not assessed only on making a final product; they are assessed across the four IBO criteria:',
  '每個準則都對應學生應提交的證據，例如設計簡介、設計規格、製作記錄與測試報告。': 'Each criterion is linked to evidence students are expected to produce, such as a design brief, design specification, making record, and testing report.',
  'Expected Evidence': 'Expected Evidence',
  'MYP → DP 銜接對照': 'MYP to DP Progression Map',
  'MYP Design Cycle': 'MYP Design Cycle',
  'DP Design Project IA 對應': 'DP Design Project IA Link',
  '核心技能': 'Core Skills',
  '學習中心 (Home)': 'Learning Hub (Home)',
  'DSE 概覽 (Home)': 'DSE Overview (Home)',
  'IB 課程概覽 (Home)': 'IB Overview (Home)',
  '學習概覽': 'Learning Overview',
  '工具箱: ': 'Toolkit: ',
  '高中學生': 'Senior Student',
  '中一 (S1)': 'Secondary 1 (S1)',
  '中二 (S2)': 'Secondary 2 (S2)',
  '中三 (S3)': 'Secondary 3 (S3)',
  '教學計劃 · 全學年33週 · 每節40分鐘': 'Teaching plan · 33 weeks across the year · 40 minutes per period',
  '每週兩節可選組合甲＋乙（共66節）；每週一節可選組合甲或組合乙': 'At two periods per week, both Core A and Core B may be offered (66 periods total); at one period per week, choose either Core A or Core B.',
  '每週兩節可選組合甲＋乙（共66節）；延伸部分另加32節（共98節）': 'At two periods per week, both Core A and Core B may be offered (66 periods total); the extension adds another 32 periods (98 total).',
  '組合甲 34節 ＋ 組合乙 46節 = 共80節': 'Core A 34 periods + Core B 46 periods = 80 periods total',
  '延伸部分另加25節（核心共66節）': 'Extension adds 25 more periods (66 core periods in total)',
  '可選延伸組合甲或組合乙，二者不並行': 'Choose either Extension A or Extension B; they are not run in parallel.',
  '教材四乙及五的專題活動為「健身公園」，建議先教E3再教K6-中三乙': 'The project activity in Teaching Packs 4B and 5 is "Fitness Park". It is recommended to teach E3 before K6-S3B.',
  '以教材六教授；K9 另設專題活動12節及個案研究5節（延伸）': 'Teach with Teaching Pack 6; K9 also includes an extension of 12 project periods and 5 case-study periods.',
  'E7 分四個教材單元（八至十一），每單元獨立施教': 'E7 is divided into four teaching units (8 to 11), and each unit can be taught independently.',
  '核心部分 組合甲 (Core A)': 'Core Part Option A',
  '核心部分 組合乙 (Core B)': 'Core Part Option B',
  '延伸部分': 'Extension Part',
  '延伸部分 組合甲 — 物料及製造': 'Extension Part Option A — Materials and Manufacturing',
  '延伸部分 組合乙 — 結構及系統': 'Extension Part Option B — Structures and Systems',
  '核心及延伸部分 組合乙 (Core + Extension B)': 'Core and Extension Part Option B',
  '增潤延伸 核心部分 (組合甲) — 系統': 'Enrichment Extension Core Part (Option A) — Systems',
  '增潤延伸 核心及延伸部分 (組合乙) — 系統整合及控制': 'Enrichment Core and Extension Part (Option B) — System Integration and Control',
  '基本的設計理念': 'Basic design concepts',
  '草繪技巧': 'Sketching skills',
  '物料的基本認識': 'Basic understanding of materials',
  '物料的特性': 'Properties of materials',
  '安全': 'Safety',
  '基本手工具': 'Basic hand tools',
  '基本量度工具': 'Basic measuring tools',
  '進行設計': 'Carrying out design',
  '使用不同的物料': 'Using different materials',
  '人的因素': 'Human factors',
  '結構和機械結構的基本概念': 'Basic concepts of structures and mechanisms',
  '系統的基本概念': 'Basic concepts of systems',
  '系統應用的基本概念': 'Basic concepts of system applications',
  '包括結構和機械結構的製作': 'Including the making of structures and mechanisms',
  '切除、成形、接合及完成處理': 'Cutting, forming, joining, and finishing',
  '系統與系統及子系統之間的聯繫': 'Links between systems and subsystems',
  '物料的特性及測試': 'Material properties and testing',
  '安全使用工具及儀器': 'Safe use of tools and instruments',
  '選取及運用合適工具、儀器和機器以實踐設計概念': 'Selecting and using suitable tools, instruments, and machines to realise design concepts',
  '基本設計元素': 'Basic design elements',
  '設計過程': 'Design process',
  '設計上的考慮': 'Design considerations',
  '結構及運動的簡單特性': 'Simple properties of structures and motion',
  '按不同需求而設計的結構': 'Structures designed for different needs',
  '應用機械結構裝置傳動及控制運動': 'Using mechanisms to transmit and control movement',
  '生活模式的改變': 'Changes in lifestyle patterns',
  '開環式及閉環式控制系統': 'Open-loop and closed-loop control systems',
  '機動式、電機式、電子式及氣動式控制系統': 'Mechanical, electrical, electronic, and pneumatic control systems',
  '控制系統模式': 'Control system models',
  '選取合適製造過程所涉及的因素及限制': 'Factors and constraints in selecting suitable manufacturing processes',
  '選擇及使用合適的物料處理過程': 'Selecting and using suitable material-processing methods',
  '計畫及組織工作的步驟或程式': 'Planning and organising work steps or procedures',
  '自動化控制': 'Automation control',
  '應用各種常見的物料': 'Applying common materials',
  '資源再用、回收及可持續發展': 'Reuse, recycling, and sustainable development',
  '應用一系列的機器以實施設計問題的方案': 'Using a range of machines to implement design solutions',
  '電腦輔助設計': 'Computer-aided design',
  'CAD立體模型': 'CAD 3D models',
  '應加強設計效果': 'Enhancing design presentation',
  '設計批判及評鑒': 'Design critique and evaluation',
  '物料接合': 'Material joining',
  '製造過程的設備': 'Manufacturing equipment',
  '物料表面處理': 'Material surface finishing',
  '產品標準': 'Product standards',
  '設計評鑒': 'Design evaluation',
  '知識產權': 'Intellectual property',
  '設計師和工程師在工作中的角色': 'The roles of designers and engineers in practice',
  '設計的演示': 'Design presentation',
  '應用於不同領域的製造過程': 'Manufacturing processes applied in different fields',
  '項目里的個體協作': 'Individual collaboration within a project',
  '系統組件': 'System components',
  '簡單系統設計的例子和子系統的分析': 'Examples of simple system design and subsystem analysis',
  '機動式、電機式、電子式及氣動式系統應用': 'Mechanical, electrical, electronic, and pneumatic system applications',
  '控制系統模式、建構模型的工具包及模擬科技的解決方案': 'Control system models, construction kits, and simulated technological solutions',
  '將互相有關聯的系統組合（應用軟體、結構和/或機械），以創建一個新的系統，並可以與其他系統連接': 'Combining related systems (software, structures, and/or mechanisms) to create a new system that can connect with other systems',
  '電腦輔助製造(CAM)及彈性製造系統(FMS)基本認知': 'Basic understanding of computer-aided manufacturing (CAM) and flexible manufacturing systems (FMS)',
  '3D立體列印基本概念': 'Basic concepts of 3D printing',
  '電腦控制基本概念（以Arduino或其他進行簡單實驗）': 'Basic concepts of computer control (with simple Arduino or similar experiments)',
  '機器人及機器人控制基本概念': 'Basic concepts of robotics and robot control',
  '相關知識 1節': 'Related knowledge 1 period',
  '相關知識 1.5節': 'Related knowledge 1.5 periods',
  '相關知識 2節': 'Related knowledge 2 periods',
  '相關知識 3節': 'Related knowledge 3 periods',
  '相關知識 4節': 'Related knowledge 4 periods',
  '相關知識 5節': 'Related knowledge 5 periods',
  '相關知識 6節': 'Related knowledge 6 periods',
  '相關知識 8節': 'Related knowledge 8 periods',
  '課堂活動 0.5節': 'Class activity 0.5 period',
  '課堂活動 1節': 'Class activity 1 period',
  '課堂活動 2節': 'Class activity 2 periods',
  '課堂活動 5節': 'Class activity 5 periods',
  '課堂活動 9節': 'Class activity 9 periods',
  '課堂練習 0.5節': 'Class exercise 0.5 period',
  '課堂練習 1節': 'Class exercise 1 period',
  '課堂練習 2節': 'Class exercise 2 periods',
  '課堂練習 3節': 'Class exercise 3 periods',
  '課堂練習 5節': 'Class exercise 5 periods',
  '課堂練習 24節': 'Class exercise 24 periods',
  '專題活動 2節': 'Project activity 2 periods',
  '專題活動 3節（與K8共用教材六）': 'Project activity 3 periods (shared with K8 in Teaching Pack 6)',
  '專題活動 4節': 'Project activity 4 periods',
  '專題活動 5節': 'Project activity 5 periods',
  '專題活動 6節': 'Project activity 6 periods',
  '專題活動 8節': 'Project activity 8 periods',
  '專題活動 9節': 'Project activity 9 periods',
  '專題活動 12節': 'Project activity 12 periods',
  '專題活動 14節': 'Project activity 14 periods',
  '專題活動 24節': 'Project activity 24 periods',
  '專題練習 7節': 'Project exercise 7 periods',
  '個案研究 2節': 'Case study 2 periods',
  '個案研究 3節': 'Case study 3 periods',
  '個案研究 5節': 'Case study 5 periods',
  '個案研究 6節': 'Case study 6 periods',
  '個案研究 7節': 'Case study 7 periods',
  '個案研究（課後進行）': 'Case study (conducted after class)',
  '(延伸) 專題活動 12節': '(Extension) Project activity 12 periods',
  '(延伸) 個案研究 5節': '(Extension) Case study 5 periods',
  'CAD練習 12節': 'CAD practice 12 periods',
};

const extractEnglish = (value: string) => {
  const match = value.match(/^(.*?)\s*\(([^()]+)\)$/);
  if (match) return match[2].trim();
  return null;
};

export const translateText = (value: string, language: AppLanguage) => {
  if (language === 'zh-HK') return value;
  return EN_TRANSLATIONS[value] ?? extractEnglish(value) ?? value;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<AppLanguage>('zh-HK');

  useEffect(() => {
    const saved = window.localStorage.getItem('app-language');
    if (saved === 'zh-HK' || saved === 'en') {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (nextLanguage: AppLanguage) => {
    setLanguageState(nextLanguage);
    window.localStorage.setItem('app-language', nextLanguage);
  };

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    isEnglish: language === 'en',
    toggleLanguage: () => setLanguage(language === 'en' ? 'zh-HK' : 'en'),
    setLanguage,
    t: (zh, en) => language === 'en' ? en : zh,
    tr: (input) => translateText(input, language),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
